### ISSUE TITLE
Chamge your ci with dotnet-releaser

### ISSUE THREAD

**Issue by xoofx** [jmanuelcorral/releasedb#1]
Hey, I saw that you are starting to experiment dotnet-releaser in your CI. The proper way to use it is like this:

```yaml
name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build, Test, Pack, Publish (on tag)
      shell: bash
      run: |
        dotnet tool install --global dotnet-releaser
        dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" src/dotnet-releaser.toml
``` 

- `fetch-depth: 0` is important for actions/checkout@v2
- `dotnet-releaser` should be able handle the entire build and publish (only on a tag) process here.
- `shell: bash` is to make sure that no matter which platform you are running on, you get a consistent behavior with double quotes `"` (unlike e.g PowerShell)
